import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles((theme) => ({
  list: {
    //color: theme.palette.primary.contrastText,
    backgroundSize: "cover",
    maxWidth: "28%",
    backgroundPosition: "50%",
    backgroundRepeat: "no-repeat",
    padding: " 10px 23px",
    height: "250",
    display: "flex",
    flexDirection: "column",
  },
  txt_1: {
    color: theme.palette.primary.main,
    fontWeight: 700,
    fontSize: "12px",
    fontStyle: "normal",
    fontFamily: theme.overrides.MuiTypography.body,
  },
  head: {
    color: theme.palette.primary.black,
    fontWeight: 400,
    fontSize: "20px",
    fontStyle: "normal",
    lineHeight: 1.3,
    fontFamily: theme.overrides.MuiTypography.fontFamily,
    margin: 0,
  },
  Price: {
    fontSize: "24px",
    fontStyle: "normal",
    lineHeight: 1.2,
    color: theme.palette.primary.main,
  },
  firstPrice1: {
    textDecoration: "line-through",
    color: theme.palette.primary.main,
  },
  firstPrice: {
    color: theme.palette.grey[200],
    fontSize: "18px",
    fontStyle: "normal",
    lineHeight: 1.2,
    fontWeight: 400,
    margin: "0px 5px",
  },
  ButtonContact: {
    fontSize: "14px",
    fontStyle: "normal",
    padding: "7px 0px",
    lineHeight: "20px",
    width: "35%",
    fontWeight: 700,
    textTransform: "none",
    fontFamily: theme.overrides.MuiTypography.fontFamily,
    "&:hover": {
      backgroundColor: theme.palette.primary.light,
      borderRadius: 4,
    },
  },
  headCard0: {
    fontWeight: 700,
    fontStyle: "normal",
    color: theme.palette.primary.main,
    fontSize: "40px",
    lineHeight: 1.1,
    margin: "0px",
    marginBottom: "25px",
    fontFamily: theme.overrides.MuiTypography.fontFamily,
  },
  ButtonAllServices: {
    fontSize: "14px",
    fontStyle: "normal",
    padding: "7px 0px",
    lineHeight: "20px",
    width: "35%",
    fontWeight: 500,
    marginTop: "25px",
    textTransform: "none",
    backgroundColor: theme.palette.primary.light,
    border: `2px solid ${theme.palette.primary.light}`,
    "&:hover": {
      backgroundColor: theme.palette.primary.contrastText,
      color: theme.palette.primary.light,
      borderRadius: 4,
    },
  },
  headCard: {
    fontWeight: 600,
    fontStyle: "normal",
    color: theme.palette.primary.main,
    fontSize: "21px",
    // lineHeight: 1.2,
    margin: "0px",
    lineHeight: 1.5,
    width: "75%",
    fontFamily: theme.overrides.MuiTypography.fontFamily,
  },
  NumCard: {
    color: theme.palette.grey[200],
    fontSize: "22px",
    fontStyle: "normal",
    lineHeight: 1.3,
    fontWeight: 700,
    fontFamily: theme.overrides.MuiTypography.fontFamily,
    textAlign: "right",
  },
  ParCard: {
    fontSize: "16px",
    fontStyle: "normal",
    lineHeight: 1.4,
    fontWeight: 400,
    color: theme.palette.grey[200],
    fontFamily: theme.overrides.MuiTypography.fontFamily,
  },
  root: {
    // display: "flex",
    // flexWrap: "wrap",
    // justifyContent: "space-around",
    // overflow: "hidden",
    // backgroundColor: theme.palette.background.paper,
  },

  cardGrid: {
    // paddingTop: theme.spacing(8),
    // paddingBottom: theme.spacing(8),
    padding: theme.spacing(8),
    [theme.breakpoints.down("md")]: {
      padding: theme.spacing(0),
      paddingTop: theme.spacing(8),
      paddingBottom: theme.spacing(8),
    },
  },
  List: {
    //padding: "0% 6%",
  },
}));

export default useStyles;
